name: Teams PR Notification

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get PR information
      id: pr-info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Get number of files changed using GitHub API
        FILES_CHANGED=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files" | \
          jq '. | length')
        
        # Get PR information from GitHub context
        AUTHOR="${{ github.event.pull_request.user.login }}"
        REPO_NAME="${{ github.repository }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        PR_DESCRIPTION="${{ github.event.pull_request.body }}"
        PR_URL="${{ github.event.pull_request.html_url }}"
        PR_NUMBER="${{ github.event.pull_request.number }}"
        
        # Handle null/empty description
        if [ -z "$PR_DESCRIPTION" ] || [ "$PR_DESCRIPTION" = "null" ]; then
          PR_DESCRIPTION="No description provided"
        fi
        
        # Set outputs (jq will handle all escaping)
        echo "files_changed=$FILES_CHANGED" >> $GITHUB_OUTPUT
        echo "author=$AUTHOR" >> $GITHUB_OUTPUT
        echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
        echo "pr_title=$PR_TITLE" >> $GITHUB_OUTPUT
        echo "pr_description=$PR_DESCRIPTION" >> $GITHUB_OUTPUT
        echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
    
    - name: Send Teams Notification
      run: |
        # Create Teams Adaptive Card JSON using jq to ensure proper escaping
        jq -n \
          --arg author "${{ steps.pr-info.outputs.author }}" \
          --arg repo "${{ steps.pr-info.outputs.repo_name }}" \
          --arg pr_number "${{ steps.pr-info.outputs.pr_number }}" \
          --arg files_changed "${{ steps.pr-info.outputs.files_changed }}" \
          --arg title "${{ steps.pr-info.outputs.pr_title }}" \
          --arg description "${{ steps.pr-info.outputs.pr_description }}" \
          --arg url "${{ steps.pr-info.outputs.pr_url }}" \
          '{
            "type": "message",
            "attachments": [
              {
                "contentType": "application/vnd.microsoft.card.adaptive",
                "content": {
                  "type": "AdaptiveCard",
                  "body": [
                    {
                      "type": "TextBlock",
                      "size": "Medium",
                      "weight": "Bolder",
                      "text": "🔄 Pull Request Update"
                    },
                    {
                      "type": "FactSet",
                      "facts": [
                        {
                          "title": "Author:",
                          "value": $author
                        },
                        {
                          "title": "Repository:",
                          "value": $repo
                        },
                        {
                          "title": "PR Number:",
                          "value": ("#" + $pr_number)
                        },
                        {
                          "title": "Files Changed:",
                          "value": $files_changed
                        }
                      ]
                    },
                    {
                      "type": "TextBlock",
                      "text": ("**Title:** " + $title),
                      "wrap": true
                    },
                    {
                      "type": "TextBlock",
                      "text": ("**Description:** " + $description),
                      "wrap": true,
                      "spacing": "Medium"
                    }
                  ],
                  "actions": [
                    {
                      "type": "Action.OpenUrl",
                      "title": "View Pull Request",
                      "url": $url
                    }
                  ],
                  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                  "version": "1.3"
                }
              }
            ]
          }' > teams_card.json
        
        # Send to Teams webhook
        curl -H "Content-Type: application/json" \
             -d @teams_card.json \
             "https://prod-186.westus.logic.azure.com:443/workflows/0ccd0444b7b14aacaf8eb7a538fbadf1/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=QG4OgiiJizvyly6-9mfTb9VLWvI034UKCP5qyvSPMY4"
        
        echo "Teams notification sent successfully!"